site_name: Gardeno's - Guia do Desenvolvedor
repo_url: https://github.com/alessfm/gardenos
repo_name: alessfm/gardenos
copyright: Copyright &copy; 2022 Alessandro F.
theme:
  language: pt-BR
  favicon: assets/Vector.svg
  logo: assets/Vector1.svg
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Trocar para modo noturno
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/eye
        name: Trocar para modo diurno
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alessfm/gardenos
      name: Repositório Oficial
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
